global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'wordpress'
    static_configs:
      - targets: ['wordpress:80']
    metrics_path: /wp-admin/admin-ajax.php
    params:
      action: ['health_check']


# WordPress мониторинг через Blackbox Exporter (для проверки доступности)
  - job_name: 'wordpress-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://wordpress:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Blackbox Exporter
  - job_name: 'blackbox'
    static_configs:
      - targets: ['blackbox-exporter:9115']
