{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sre-app.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sre-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ if eq .path "/admin" }}{{ include "sre-app.goApp.name" $ }}{{ else }}{{ include "sre-app.flaskApp.name" $ }}{{ end }}
                port:
                  number: {{ if eq .path "/admin" }}{{ $.Values.goApp.service.port }}{{ else }}{{ $.Values.flaskApp.service.port }}{{ end }}
        {{- end }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}